### PR TITLE
BasicRunTest: use Assert::type

### PR DESCRIPTION
**Pull request by CZechBoY**
also fixed type of $file in phpdoc

### CODE REVIEW

**Comment by CZechBoY** [comment]
btw why is allowed to fail tests for php 5.4-5.5 when in readme is minimal version PHP 5.3?

**Comment by h4kuna** [comment]
I have one friend who has php 5.3

**Comment by h4kuna** [comment]
ok I can create new tag without support php 5.3

**Comment by h4kuna** [comment]
i try add support 5.4 and 5.5 because extension is very easy

**Comment by h4kuna** [comment]
Thank you

**Comment by CZechBoY** [comment]
I totally know why you are supporting php5.3, but tests are failing because of `::class`, i think...

**Comment by h4kuna** [comment]
You have right. I thinking about it, i will support only supported php, then other developers on old php has motivation for update. :)

**Pull request merged**
